### PR TITLE
ESM exports + updates

### PR DESCRIPTION
**Pull request by atk**
- update dependencies
- add esm exports, fixes issue #8

### CODE REVIEW

**Comment by atk** [comment]
That is actually not neccessary if we omit type: "module" and thus, don't force node into a certain mode. Tested it again and it seems to work.

**Comment by sheremet-va** [comment]
> That is actually not neccessary if we omit type: "module" and thus, don't force node into a certain mode. Tested it again and it seems to work.

Then I don't think ESM will work :)
If you need dual support, one of them should be names cjs or mjs (depending on the base).

At least Vitest will default to `cjs` with this config, since importing _exact file_ (not `module`) will throw

**Comment by atk** [comment]
OK, I changed the exports to cjs and mjs so vitest and node may detect it properly; also increased the required node version to at least 14 to switch to a version that even allows these imports.

**Comment by ryansolid** [comment]
Thank you

**Pull request merged**
